### PR TITLE
Add @cnndatagraphics Twitter account

### PR DESCRIPTION
**Pull request by palewire**

### CODE REVIEW

**Comment by palewire** [comment]
I noticed that CNN's live election results from the House speaker contest didn't show up in your helpful feed. I see it was highlighted in their Twitter feed. I wonder if adding it as a secondary source might supplement what you provide. Would it introduce duplicates or otherwise cause problems?

**Comment by sammorrisdesign** [comment]
Thanks for the PR!

Duplicate sources will definitely break `npm run test`, although very fixable, but it _shouldn't_ result in duplicate articles as long as the urls from both sources match. However, having multiple sources for one newsroom, makes the case to refactor `config.json` with an array of sources for each publication. And I do see a strong case for multiple sources, even if it would increase the time the scripts take to fetch.

I'll run some tests with on this later today.

**Comment by palewire** [comment]
Cool. You want another PR that adds tests via Action on every push?

**Comment by sammorrisdesign** [comment]
Going to merge this into a separate branch to play around with a refactor.

On the tests: the tests are the moment are more for safely checking if a config is correct. Rather than a unit test or something like that. So I _think_ it's ok as it is.

**Pull request merged**
