### PR TITLE
New publication: Les Échos

### PR DESCRIPTION
**Pull request by TomFevrier**
- Adding new publication: Les Échos
- Fixing README: in `"type": "Twitter"`, Twitter should be capitalized

### CODE REVIEW

**Comment by sammorrisdesign** [comment]
Thanks for the submission. After a quick look through it looks like the articles served from media.lesechos.fr are the interactives. Is that accurate?

**Comment by TomFevrier** [comment]
> Thanks for the submission. After a quick look through it looks like the articles served from media.lesechos.fr are the interactives. Is that accurate?

Do you mean [https://media.lesechos.fr/infographie/](https://media.lesechos.fr/infographie/) ? Not necessarily, as this page is not always up to date (at this point, it has not been updated in over a year). The Twitter account is more reliable, I think.

**Comment by sammorrisdesign** [comment]
I mean articles served from that domain specifically. Like this: https://media.lesechos.fr/infographie/9h-halles/

Twitter is definitely a better source in general (unless xml or rss is available)

**Comment by TomFevrier** [comment]
> I mean articles served from that domain specifically. Like this: https://media.lesechos.fr/infographie/9h-halles/

That's right. Including full-page interactives and interactive charts embedded in stories.

**Pull request merged**
